numeros = [1, 2, 3]
letras = ["a", "b", "c"]
palabras = ["Chanchito", "feliz"]
palabrasFelices = ["Chanchito", "feliz", "Felipe", "ALumno"]
booleans = [True, False, True, True]
matriz = [[0, 1], [1, 0]]
ceros = [0] * 10  # Rellenar con 10 ceros
ceros1 = [0, 1] * 10  # Rellner con 10 0´s y 1´s
alfanumerico = numeros + letras  # Unión de las listas
rango = list(range(1, 11))  # Creación de una lista con 10 elementos
chars = list("Hola Mundo")
